### PR TITLE
Try to unbreak CI

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by elharo** [comment]
Progress! This moves us to the next error:

```
 Error:  Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:stage (default-cli) on project doxia-site: Error uploading site: Error copying directory structure: Unknown file type: /home/runner/work/maven-doxia-site/maven-doxia-site/target/site/doxia-tools/doxia-book-renderer -> [Help 1]
```

**Comment by elharo** [comment]
and the next one:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:stage (default-cli) on project doxia-site: Error uploading site: Error copying directory structure: Unknown file type: /home/runner/work/maven-doxia-site/maven-doxia-site/target/site/doxia-tools/doxia-linkcheck -> [Help 1]
```

**Comment by elharo** [comment]
Possible this is an issue with symlink handling in the site plugin

**Comment by elharo** [comment]
problem could be here in FileWagon:

       try
        {
            FileUtils.copyDirectoryStructure( sourceDirectory, path );
        }
        catch ( IOException e )
        {
            throw new TransferFailedException( "Error copying directory structure", e );
        }

**Comment by elharo** [comment]
Caused by: java.io.IOException: Unknown file type: /home/runner/work/maven-doxia-site/maven-doxia-site/target/site/doxia
    at org.codehaus.plexus.util.FileUtils.copyDirectoryStructure (FileUtils.java:2088)
    at org.codehaus.plexus.util.FileUtils.copyDirectoryStructure (FileUtils.java:1999)
    at org.apache.maven.wagon.providers.file.FileWagon.putDirectory (FileWagon.java:193)

**Comment by elharo** [comment]
This is the PLexus code so I'm betting it's dying on a symlink:

```
        if ( file.isFile() )
            {
                destination = destination.getParentFile();

                if ( onlyModifiedFiles )
                {
                    copyFileToDirectoryIfModified( file, destination );
                }
                else
                {
                    copyFileToDirectory( file, destination );
                }
            }
            else if ( file.isDirectory() )
            {
                if ( !destination.exists() && !destination.mkdirs() )
                {
                    throw new IOException( "Could not create destination directory '" + destination.getAbsolutePath()
                        + "'." );
                }

                copyDirectoryStructure( file, destination, rootDestinationDirectory, onlyModifiedFiles );
            }
            else
            {
                throw new IOException( "Unknown file type: " + file.getAbsolutePath() );
            }
        }
```

**Comment by slachiewicz** [comment]
i hope ci should be ok now, please rebase and squash Your changes

**Review by elharo — COMMENTED** [review]
PTAL. Merged to master

**Review by slachiewicz — APPROVED** [review]

**Pull request merged**
