### PR TITLE
Explain table headers

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by kwin** [comment]
I just figured out this is actually already explained in https://maven.apache.org/doxia/references/doxia-apt.html#Table_header_cells. The separation between original APT and extension into two different pages makes the documentation for newbies who just want to write APT for Doxia a bit hard to digest.

**Comment by michael-o** [comment]
The question which I have already discussed with @hboutemy. Does it still make sense to promote APT? What does it offer what Asciidoctor and Markdown don't offer?

**Comment by kwin** [comment]
This is an orthogonal discussion. Every format supported by Doxia needs to have proper documentation (either in Maven or with a reliable external source). As for APT I found no other reliable source, the APT documentation should stay as long as Doxia supports it. Maybe some deprecation notice can be added at the beginning of the page though...

**Comment by michael-o** [comment]
> This is an orthogonal discussion. Every format supported by Doxia needs to have proper documentation (either in Maven or with a reliable external source). As for APT I found no other reliable source, the APT documentation should stay as long as Doxia supports it. Maybe some deprecation notice can be added at the beginning of the page though...

Agree. Documentation should be decent.

**Pull request closed without merging**
